### ISSUE TITLE
Remove "Infra Points" from national intelligence effects

### ISSUE THREAD

**Issue by jwrober** [longturn/LTT-LTX#15]
We got rid of infra points in the fc21 code, so we should remove references to Infra Points in effects.ruleset for all of our rulesets (including LTT/LTX in games repo if its there)

**Comment by blabber** [comment]
Infra points have been removed from all rulesets in be62af972d109ef5c87f4fde9ca76bded009b308.

I just noticed now the existence of this issue and therefore didn't close this issue with the commit. It needs to be closed manually.

**Comment by psampathkumar** [comment]
Thanks!
