### ISSUE TITLE
Figure out what to do with Funda/Crusaders/Fanatics

### ISSUE THREAD

**Issue by lmoureaux** [longturn/LTT-LTX#9]
Funda is currently useless.

One suggestion is to make it a government you can use to stop a greatly superior attack. For this crusaders/fanatics would need to be reasonably cheap and have very good defense (defend ok against a musk or frigate). Something like A2 D3 HP10 and a 2x defense bonus in player's own cities while in Funda. So extremely defense oriented at the cost of 4 turns of Anarchy and a lot less science. They should also be reasonably cheap so they can be produced while under attack.

**Comment by jwrober** [comment]
Maybe a dup? See #6

**Comment by lmoureaux** [comment]
100% a dup.
